apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner
      containers:
        - name: runner
          image: myoung34/github-runner:latest
          env:
            - name: RUNNER_SCOPE
              value: repo
            - name: REPO_URL
              value: https://github.com/J4yM1l/codejourney-ops
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: runner-secrets
                  key: ACCESS_TOKEN
            - name: RUNNER_NAME
              value: k3s-homelab
            - name: RUNNER_LABELS
              value: self-hosted,k3s-gitops
            - name: DISABLE_AUTO_UPDATE
              value: "true"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 2Gi
